using System;

namespace LlamaParse;

internal static class LanguagesExtensions
{
    public static string ToLanguageCode(this Languages language) => language switch
    {
        Languages.Baza => "abq",
        Languages.Adyghe => "ady",
        Languages.Afrikaans => "af",
        Languages.Angika => "ang",
        Languages.Arabic => "ar",
        Languages.Assamese => "as",
        Languages.Avar => "ava",
        Languages.Azerbaijani => "az",
        Languages.Belarusian => "be",
        Languages.Bulgarian => "bg",
        Languages.Bihari => "bh",
        Languages.Bhojpuri => "bho",
        Languages.Bengali => "bn",
        Languages.Bosnian => "bs",
        Languages.SimplifiedChinese => "ch_sim",
        Languages.TraditionalChinese => "ch_tra",
        Languages.Chechen => "che",
        Languages.Czech => "cs",
        Languages.Welsh => "cy",
        Languages.Danish => "da",
        Languages.Dargwa => "dar",
        Languages.German => "de",
        Languages.English => "en",
        Languages.Spanish => "es",
        Languages.Estonian => "et",
        Languages.PersianFarsi => "fa",
        Languages.French => "fr",
        Languages.Irish => "ga",
        Languages.GoanKonkani => "gom",
        Languages.Hindi => "hi",
        Languages.Croatian => "hr",
        Languages.Hungarian => "hu",
        Languages.Indonesian => "id",
        Languages.Ingush => "inh",
        Languages.Icelandic => "is",
        Languages.Italian => "it",
        Languages.Japanese => "ja",
        Languages.Kabardian => "kbd",
        Languages.Kannada => "kn",
        Languages.Korean => "ko",
        Languages.Kurdish => "ku",
        Languages.Latin => "la",
        Languages.Lak => "lbe",
        Languages.Lezghian => "lez",
        Languages.Lithuanian => "lt",
        Languages.Latvian => "lv",
        Languages.Magahi => "mah",
        Languages.Maithili => "mai",
        Languages.Maori => "mi",
        Languages.Mongolian => "mn",
        Languages.Marathi => "mr",
        Languages.Malay => "ms",
        Languages.Maltese => "mt",
        Languages.Nepali => "ne",
        Languages.Newari => "new",
        Languages.Dutch => "nl",
        Languages.Norwegian => "no",
        Languages.Occitan => "oc",
        Languages.Pali => "pi",
        Languages.Polish => "pl",
        Languages.Portuguese => "pt",
        Languages.Romanian => "ro",
        Languages.Russian => "ru",
        Languages.SerbianCyrillic => "rs_cyrillic",
        Languages.SerbianLatin => "rs_latin",
        Languages.Nagpuri => "sck",
        Languages.Slovak => "sk",
        Languages.Slovenian => "sl",
        Languages.Albanian => "sq",
        Languages.Swedish => "sv",
        Languages.Swahili => "sw",
        Languages.Tamil => "ta",
        Languages.Tabassaran => "tab",
        Languages.Telugu => "te",
        Languages.Thai => "th",
        Languages.Tajik => "tjk",
        Languages.Tagalog => "tl",
        Languages.Turkish => "tr",
        Languages.Uyghur => "ug",
        Languages.Ukrainian => "uk",
        Languages.Urdu => "ur",
        Languages.Uzbek => "uz",
        Languages.Vietnamese => "vi",
        _ => throw new ArgumentOutOfRangeException(nameof(language), language, null)
    };
}
