<?xml version="1.0" encoding="utf-8"?>
<Project>

	<!-- this file specifies a set of common properties imported by all projects in the folder -->
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Company>LlamaIndex</Company>
		<!-- IsPackable is enabled for all the projects and enabled only for the actual libraries -->
		<IsPackable>false</IsPackable>
	</PropertyGroup>

</Project>
