name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Install .NET Aspire workload
      run: dotnet workload install aspire
    
    - name: Set version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${VERSION}
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output nupkgs /p:Version=${VERSION}
    
    - name: Push to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate